# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       qtcontacts-tracker

# >> macros
# << macros

Summary:    QtContact tracker storage plugin
Version:    4.19.2
Release:    1
Group:      System/Libraries
License:    LGPL v2.1
URL:        http://gitorious.org/qtcontacts-tracker
Source0:    qtcontacts-tracker-%{version}.tar.gz
Source100:  qtcontacts-tracker.yaml
Patch0:     qtcontacts-tracker-4.16.1-fix-linking.patch
Patch1:     qtcontacts-tracker-4.19.2-fix-private-dtor-in-thread-local-storage-class.patch
Patch2:     qtcontacts-tracker-4.19.2-fix-broken-docs-check-we-don-t-want-them.patch
Patch3:     qtcontacts-tracker-4.19.2-fix-field-extended-address-reference.patch
Patch4:     0001-Fix-QObject-thread-ownership-issues.patch
Patch5:     qtcontacts-tracker-4.19.2-compile-against-tracker-0.14.patch
Patch6:     qtcontacts-tracker-4.19.2-no-su-for-tests.patch
Requires:   libqtsparql-tracker >= 0.0.18
Requires:   libqtsparql-tracker-direct
BuildRequires:  pkgconfig(QtContacts) >= 1.2
BuildRequires:  pkgconfig(QtSparql) >= 0.0.18
BuildRequires:  pkgconfig(QtSparqlTrackerExtensions) >= 0.0.5
BuildRequires:  pkgconfig(QtCore) >= 4.6.0
BuildRequires:  pkgconfig(QtDBus)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  libcubi-devel >= 0.1.14
BuildRequires:  tracker-devel >= 0.10.6
BuildRequires:  libcubi-tracker-ontologies-devel >= 0.1.4
BuildRequires:  fdupes
BuildRequires:  python

%description
QtContact tracker storage plugin.

%package -n libqtcontacts-tracker-extensions
Summary:    Specific QContact extensions from qtcontacts-tracker
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtcontacts-tracker-extensions
The qtcontacts-tracker-extensions provides additionnal functions and
constants used by qtcontacts-tracker, but not part of the official QContact API.


%package tests
Summary:    Tests for QtContact tracker storage plugin
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description tests
Tests package for QtContact tracker storage plugin.

%package -n libqtcontacts-tracker-extensions-devel
Summary:    Development files for libqtcontacts-tracker-extensions
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libqtcontacts-tracker-extensions = %{version}-%{release}
Requires:   libcubi-devel >= 0.1.7

%description -n libqtcontacts-tracker-extensions-devel
The qtcontacts-tracker-extensions-devel package includes the header files
for qtcontacts-tracker-extensions.


%package benchmarks
Summary:    Benchmarks for QtContact tracker storage plugin
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description benchmarks
Benchmarks package for QtContact tracker storage plugin.

%prep
%setup -q -n %{name}-%{version}/%{name}

# qtcontacts-tracker-4.16.1-fix-linking.patch
%patch0 -p1
# qtcontacts-tracker-4.19.2-fix-private-dtor-in-thread-local-storage-class.patch
%patch1 -p1
# qtcontacts-tracker-4.19.2-fix-broken-docs-check-we-don-t-want-them.patch
%patch2 -p1
# qtcontacts-tracker-4.19.2-fix-field-extended-address-reference.patch
%patch3 -p1
# 0001-Fix-QObject-thread-ownership-issues.patch
%patch4 -p1
# qtcontacts-tracker-4.19.2-compile-against-tracker-0.14.patch
%patch5 -p1
# qtcontacts-tracker-4.19.2-no-su-for-tests.patch
%patch6 -p1
# >> setup
# << setup

%build
# >> build pre
echo "QMAKE_CXXFLAGS *= -g" > user.pri
echo "QMAKE_STRIP = echo" >> user.pri
./configure --prefix %{_prefix} --disable-builddirs-rpath --disable-schemalist
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

%fdupes  %{buildroot}/%{_datadir}/libqtcontacts-tracker-tests/

# << install post

%post -n libqtcontacts-tracker-extensions -p /sbin/ldconfig

%postun -n libqtcontacts-tracker-extensions -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/qt4/plugins/contacts/libqtcontacts_tracker.so
%exclude %{_datadir}/backup-framework/applications/libqtcontacts-tracker.conf
# << files

%files -n libqtcontacts-tracker-extensions
%defattr(-,root,root,-)
# >> files libqtcontacts-tracker-extensions
%{_libdir}/libqtcontacts_extensions_tracker.so.*
# << files libqtcontacts-tracker-extensions

%files tests
%defattr(-,root,root,-)
# >> files tests
%{_bindir}/ut_*
%{_datadir}/libqtcontacts-tracker-tests/*
# << files tests

%files -n libqtcontacts-tracker-extensions-devel
%defattr(-,root,root,-)
# >> files libqtcontacts-tracker-extensions-devel
%{_libdir}/libqtcontacts_extensions_tracker.so
%{_libdir}/libqtcontacts_extensions_tracker.prl
%{_includedir}/qtcontacts-tracker/*
%{_datadir}/qt4/mkspecs/features/*
# << files libqtcontacts-tracker-extensions-devel

%files benchmarks
%defattr(-,root,root,-)
# >> files benchmarks
%{_bindir}/bm_*
# << files benchmarks
